# github actions workflow used for building a new docker image of tesseract-olap cube when there is a push maked to the develop branch 
# with detected changes on the schema.xml file or the Dockerfile. after the building it's compleated, the workflow deploys that image 
# on a GOOGLE CLOUD RUN instance with the respective keys storaged on the github secrets from the repository page.
name: "[GCP] Build and Deploy Tesseract-Olap Image"

# trigger the workflow when a pull request is accepted and merged on to the develop branch
on:
  pull_request:
    branches:
      - develop 
    types: [closed]

# environment variables used on the respective workflow
env:
  # docker variables
  IMAGE_NAME: tesseract-template-image
  # google cloud platform credentials (they come from github secrets)
  GCP_ARTIFACT_REGISTRY_REPO_NAME: ${{ secrets.GCP_ARTIFACT_REGISTRY_REPO_NAME }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  # tesseract-olap environment variables
  TESSERACT_DEBUG: true
  TESSERACT_RUST_LOG: debug
  TESSERACT_SERVICE_NAME: tesseract-olap-dev

jobs:
  # builds the new docker image via google cloude build
  build:
    name: Build Docker Image via Cloud Build
    runs-on: ubuntu-latest
    environment: develop_environment
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Docker Image
        run: |-
          gcloud builds submit \
            --quiet \
            --tag us-central1-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_REGISTRY_REPO_NAME/$IMAGE_NAME:latest-dev

  # deploys the recently created docker image via google cloude build
  deploy:
    needs: build
    name: Deploy Docker Image to Cloud Run
    runs-on: ubuntu-latest
    environment: develop_environment
    steps:
      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Deploy Image to Cloud Run
        run: |-
          gcloud run deploy ${{ env.TESSERACT_SERVICE_NAME }} \
            --image=us-central1-docker.pkg.dev/${{env.GCP_PROJECT_ID}}/${{env.GCP_ARTIFACT_REGISTRY_REPO_NAME}}/${{env.IMAGE_NAME}}:latest-dev \
            --region=us-central1 \
            --port=7777 \
            --min-instances=0 \
            --max-instances=2 \
            --allow-unauthenticated \
            --set-env-vars=TESSERACT_DATABASE_URL=${{secrets.TESSERACT_DATABASE_URL}} \
            --set-env-vars=TESSERACT_DEBUG=${{env.TESSERACT_DEBUG}} \
            --set-env-vars=RUST_LOG=${{env.TESSERACT_RUST_LOG}} 
